---
title: "Annotated Bibliography"
bibliography: references.bib
csl: chicago-syllabus.csl
suppress-bibliography: true
link-citations: false
citations-hover: false
---

# Annual Review Article

@spiegelhalterRiskUncertaintyCommunication2017

# References

-   Summary: The main idea David Spiegelhalter wants the reader to be aware of is to simply to be clear about what you are trying to achieve, and make sure you actually are doing that. It is important to keep things simple and state the absolute risk of an occurrence, as well as being modest and stating that there is uncertainty in order to not risk your credibility in the future. Some more technical metrics can be used for more knowledgeable audiences, however this can exclude others by making things too complicated for them. These methods can be used to discuss risk and uncertainty clearly about many possible outcomes in natural disasters, industrial risks, and global risks.

-   Reliability and relationship to the topic: The author is recognized in his role as a leading expert in risk communication, statistics, and uncertainty analysis. He has works that come from his academic background, extensive research contributions, professional affiliations, and public engagement in statistical communication. This article has also been cited over 130 times with some articles being related to discussing the risk of a cancer, illness, or similar uncertainty.

-   Missing pieces

    -   Fractional odds, moneyline odds, and decimal odds are weird formats and probability that I still don't understand

    -   There are three catergory levels of uncertainty that I still don't understand with little examples
